name = "plinkocasino-bonus-fr"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=plinkocasino-bonus.fr"
HMAC_KEY = "360b34bbb9d769c4d96c27a684694e9f14414a3bf8ea60a96cc7fd86ef2f0ce1"
COOKIE_NAME = "tqi"
PLAY_PATH = "play-now"
BUTTON_ID = "p3114f517b68c724af7a0236c5d0d12db"
GATE_SALT = "6a8dff92390baa3a"
